ARG GO_VERSION

FROM golang:${GO_VERSION}-alpine AS builder

RUN apk update && apk add alpine-sdk git && rm -rf /var/cache/apk/*
COPY . /firesert
WORKDIR /firesert
RUN go mod download
EXPOSE 8080
CMD ["go", "test", "--tags=integration"]